Fix Cypress job to execute tests and upload results

diff --git a/.github/workflows/nextjs-project-improvements_workflow.yml b/.github/workflows/nextjs-project-improvements_workflow.yml
--- a/.github/workflows/nextjs-project-improvements_workflow.yml
+++ b/.github/workflows/nextjs-project-improvements_workflow.yml
@@ -29,6 +29,9 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Install dependencies
+        run: npm install
+
       - name: Run Cypress tests
         uses: cypress-io/github-action@v4
         with:
@@ -39,7 +42,7 @@ jobs:
       - name: Save Cypress results to artifact
         run: |
           echo "Saving Cypress results..."
-          npx cypress run --spec 'spec: cypress/integration/1-my-tests/**/*.spec.js' > result.txt
+          npx cypress run --spec 'cypress/integration/1-my-tests/**/*.spec.js' > result.txt || echo "Cypress tests failed"
         continue-on-error: true
 
       - name: Upload Cypress artifact
