Add metrics_job to workflow and update README metrics integration

diff --git a/.github/workflows/nextjs-project-improvements_workflow.yml b/.github/workflows/nextjs-project-improvements_workflow.yml
--- a/.github/workflows/nextjs-project-improvements_workflow.yml
+++ b/.github/workflows/nextjs-project-improvements_workflow.yml
@@ -119,7 +119,7 @@ jobs:
           vercel-args: "--prod"
 
   notification_job:
-    needs: [linter_job, cypress_job, add_badge_job, deploy_job]
+    needs: [linter_job, cypress_job, add_badge_job, deploy_job, metrics_job]
     runs-on: ubuntu-latest
     if: always()
     steps:
@@ -131,12 +131,12 @@ jobs:
           JOB_RESULTS+=" - cypress_job: ${{ needs.cypress_job.result }}\n"
           JOB_RESULTS+=" - add_badge_job: ${{ needs.add_badge_job.result }}\n"
           JOB_RESULTS+=" - deploy_job: ${{ needs.deploy_job.result }}\n"
+          JOB_RESULTS+=" - metrics_job: ${{ needs.metrics_job.result }}\n"
           curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
             -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
             -d text="$(echo -e "$JOB_RESULTS")"
 
   metrics_job:
-    needs: [linter_job, cypress_job]
     runs-on: ubuntu-latest
     environment:
       name: production
@@ -146,25 +146,26 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Generate GitHub metrics
+      - name: Most used
         uses: lowlighter/metrics@latest
         with:
+          filename: metrics.plugin.languages.svg
           token: ${{ secrets.METRICS_TOKEN }}
-          user: ${{ github.repository_owner }}
-          template: "languages"
-          base: "header, activity, languages"
-          config_timezone: "Europe/Madrid"
-          plugin_languages: "true"
+          base: ""
+          plugin_languages: yes
+          plugin_languages_ignored: >-
+            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
+            gnuplot
+          plugin_languages_limit: 4
 
       - name: Update README with metrics
         run: |
           echo "Updating README.md with metrics..."
-          # Agregamos las métricas al final del README.md
           echo "\n\n![Metrics](https://github.com/${{ github.repository_owner }}/${{ github.repository }}/blob/main/github-metrics.svg)" >> README.md
           git config --global user.email "alvgarcam@alu.edu.gva.es"
           git config --global user.name "AlvaroGarCam"
           git add README.md
-          git commit -m "Update README.md with GitHub metrics" || echo "No changes to commit"
+          git commit -m "Prepare for pull rebase" || echo "No changes to commit"
           git fetch origin main
-          git rebase origin/main || (git rebase --abort && echo "Rebase failed; skipping rebase")
-          git push origin main || echo "Push failed; skipping push"
+          git rebase origin/main || (git rebase --abort && echo "Rebase failed; skipping pull step")
+          git push origin main
