Add metrics_job for GitHub metrics

diff --git a/.github/workflows/nextjs-project-improvements_workflow.yml b/.github/workflows/nextjs-project-improvements_workflow.yml
--- a/.github/workflows/nextjs-project-improvements_workflow.yml
+++ b/.github/workflows/nextjs-project-improvements_workflow.yml
@@ -87,9 +87,9 @@ jobs:
         run: |
           echo "Updating README.md with badge..."
           if [ "${{ steps.read_result.outputs.cypress_outcome }}" = "failure" ]; then
-            echo "RESULTAT DELS ÚLTIMS TESTS![Test Badge](https://img.shields.io/badge/test-failure-red)" >> README.md
+            echo "RESULTAT DELS ÚLTIMS TESTS\n![Test Badge](https://img.shields.io/badge/test-failure-red)" >> README.md
           else
-            echo "RESULTAT DELS ÚLTIMS TESTS![Test Badge](https://img.shields.io/badge/tested%20with-Cypress-04C38E.svg)" >> README.md
+            echo "RESULTAT DELS ÚLTIMS TESTS\n![Test Badge](https://img.shields.io/badge/tested%20with-Cypress-04C38E.svg)" >> README.md
           fi
 
       - name: Commit updated README
@@ -99,10 +99,10 @@ jobs:
           git config --global user.email "alvgarcam@alu.edu.gva.es"
           git config --global user.name "AlvaroGarCam"
           git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
-          git remote -v
+          git pull --rebase origin main
           git add README.md
           git commit -m "Update README.md with Cypress test results" || echo "No changes to commit"
-          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} main
+          git push origin main
 
   deploy_job:
     needs: cypress_job
@@ -132,7 +132,6 @@ jobs:
           JOB_RESULTS+=" - cypress_job: ${{ needs.cypress_job.result }}\n"
           JOB_RESULTS+=" - add_badge_job: ${{ needs.add_badge_job.result }}\n"
           JOB_RESULTS+=" - deploy_job: ${{ needs.deploy_job.result }}\n"
-          echo -e "$JOB_RESULTS"
           curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
             -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
             -d text="$(echo -e "$JOB_RESULTS")"
@@ -165,5 +164,5 @@ jobs:
           git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
           git pull --rebase origin main
           git add README.md
-          git commit -m "Update README.md with GitHub metrics" || echo "No changes to commit"
+          git commit -m "Prepare for pull rebase" || echo "No changes to commit"
           git push origin main
